//! In-process llama.cpp runtime for local chat and embeddings.
use std::{
    path::Path,
    sync::{Arc, LazyLock, Mutex},
    time::Instant,
};

use super::{
    ChatModel, ChatRequest, EMBEDDING_DIM, Embedder, EngineError, EngineResult, Flow,
    GenerationStats, RgbImage, Transcriber,
};
use llama_cpp_2::{
    LogOptions,
    context::{
        LlamaContext,
        params::{LlamaContextParams, LlamaPoolingType},
    },
    llama_backend::LlamaBackend,
    llama_batch::LlamaBatch,
    model::{LlamaModel, params::LlamaModelParams},
    mtmd::{
        MtmdBitmap, MtmdContext, MtmdContextParams, MtmdInputChunks, MtmdInputText,
        mtmd_default_marker,
    },
    sampling::LlamaSampler,
    send_logs_to_tracing,
    token::{LlamaToken, data::LlamaTokenData, data_array::LlamaTokenDataArray},
};
fn token_text_piece(
    vocab: &llama_cpp_2::vocab::LlamaVocab<'_>,
    token: llama_cpp_2::token::LlamaToken,
    raw: &mut Vec<u8>,
    pending: &mut Vec<u8>,
) -> EngineResult<usize> {
    raw.clear();
    vocab.token_to_piece_into(token, raw, false, None);
    pending.extend_from_slice(raw);
    match std::str::from_utf8(pending) {
        Ok(text) => Ok(text.len()),
        Err(error) if error.error_len().is_none() => Ok(error.valid_up_to()),
        Err(error) => Err(runtime_error(format!(
            "invalid UTF-8 generated by model: {error}"
        ))),
    }
}

fn strip_surrounding_quotes(text: &str) -> &str {
    let trimmed = text.trim();
    for (opening, closing) in [('"', '"'), ('\'', '\''), ('“', '”'), ('‘', '’')] {
        if trimmed.starts_with(opening) && trimmed.ends_with(closing) && trimmed.len() >= 2 {
            return trimmed[opening.len_utf8()..trimmed.len() - closing.len_utf8()].trim();
        }
    }
    trimmed
}

static BACKEND: LazyLock<Result<Arc<LlamaBackend>, String>> = LazyLock::new(|| {
    LlamaBackend::init()
        .map(Arc::new)
        .map_err(|error| error.to_string())
});
const CHAT_CONTEXT: u32 = 4096;
/// bge-small-en-v1.5 reads at most 512 tokens (BERT positions); longer input is cut.
const EMBED_CONTEXT: u32 = 512;
/// Gemma audio transcription context.
const TRANSCRIBE_CONTEXT: u32 = 2048;

/// Initialized llama.cpp backend shared by all loaded models.
#[derive(Clone)]
pub struct Runtime {
    backend: Arc<LlamaBackend>,
}

impl Runtime {
    /// Initializes llama.cpp and routes its logs through tracing.
    ///
    /// # Errors
    /// Returns a runtime error if the backend cannot be initialized.
    pub fn init() -> EngineResult<Self> {
        send_logs_to_tracing(LogOptions::default());
        let backend = BACKEND
            .as_ref()
            .map_err(|error| EngineError::Runtime(error.clone()))?;
        Ok(Self {
            backend: Arc::clone(backend),
        })
    }
}

fn runtime_error(error: impl std::fmt::Display) -> EngineError {
    EngineError::Runtime(error.to_string())
}
fn threads() -> i32 {
    std::thread::available_parallelism().map_or(1, |n| i32::try_from(n.get()).unwrap_or(i32::MAX))
}

fn load_model(rt: &Runtime, path: &Path, layers: u32) -> EngineResult<LlamaModel> {
    if !path.is_file() {
        return Err(EngineError::MissingModel(path.display().to_string()));
    }
    LlamaModel::load_from_file(
        &rt.backend,
        path,
        &LlamaModelParams::default().with_n_gpu_layers(layers),
    )
    .map_err(runtime_error)
}
fn context<'a>(
    model: &'a LlamaModel,
    backend: &LlamaBackend,
    size: u32,
    embeddings: bool,
    pooling: LlamaPoolingType,
) -> EngineResult<LlamaContext<'a>> {
    let n_ctx = std::num::NonZeroU32::new(size);
    let params = LlamaContextParams::default()
        .with_n_ctx(n_ctx)
        .with_n_threads(threads())
        .with_n_threads_batch(threads())
        .with_embeddings(embeddings)
        .with_pooling_type(pooling);
    // Vulkan's flash-attention kernels are slower than plain attention on laptop GPUs
    // without matrix cores: on Intel Iris Xe, "auto" read a 150-element screen
    // (2,945 tokens) at 53 tokens/s and disabled at 150 tokens/s (MODELS.md). Only
    // Iris Xe was measured; other Windows GPUs get the same setting.
    #[cfg(target_os = "windows")]
    let params = params.with_flash_attention_policy(FLASH_ATTENTION_DISABLED);
    model.new_context(backend, params).map_err(runtime_error)
}

/// llama.cpp's `LLAMA_FLASH_ATTN_TYPE_DISABLED`.
#[cfg(target_os = "windows")]
const FLASH_ATTENTION_DISABLED: i32 = 0;

/// GPU memory left free for the system and the models already loaded.
const GPU_HEADROOM: u64 = 256 << 20;

/// Free memory of the GPU llama.cpp offloads to (shared memory on an integrated
/// GPU), or `None` without one.
pub(crate) fn gpu_free_bytes() -> Option<u64> {
    llama_cpp_2::list_llama_ggml_backend_devices()
        .into_iter()
        .find(|d| {
            matches!(
                d.device_type,
                llama_cpp_2::LlamaBackendDeviceType::Gpu | llama_cpp_2::LlamaBackendDeviceType::IntegratedGpu
            )
        })
        .map(|d| d.memory_free as u64)
}

/// Size of `path` on disk, 0 when unreadable.
pub(crate) fn file_bytes(path: &Path) -> u64 {
    std::fs::metadata(path).map_or(0, |m| m.len())
}

/// Chat model loaded from a GGUF file.
///
/// `session` and `mtmd` hold pointers into `model`; they are declared first so
/// Rust drops them before it.
pub struct LlamaChat {
    session: Mutex<Session>,
    mtmd: Option<Mutex<MtmdContext>>,
    model: Box<LlamaModel>,
    backend: Arc<LlamaBackend>,
    device: &'static str,
    format: PromptFormat,
}

/// How a model's turns are written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PromptFormat {
    /// Gemma 4 `<|turn>role … <turn|>` (Gemma 4 E2B).
    Gemma4,
    /// ChatML `<|im_start|>role … <|im_end|>` (Qwen-family models: Qwen3-VL).
    ChatMl,
}

impl PromptFormat {
    /// The prompt up to the end of the user's text. An empty `system` is left out.
    fn prefix(self, system: &str, user: &str) -> String {
        match self {
            Self::Gemma4 => gemma4_prefix(Some(system), user),
            Self::ChatMl => {
                let mut prompt = String::with_capacity(system.len() + user.len() + 64);
                if !system.is_empty() {
                    prompt.push_str("<|im_start|>system\n");
                    prompt.push_str(system);
                    prompt.push_str("<|im_end|>\n");
                }
                prompt.push_str("<|im_start|>user\n");
                prompt.push_str(user);
                prompt
            }
        }
    }

    /// End of the user turn and start of the model's reply.
    fn reply(self) -> &'static str {
        match self {
            Self::Gemma4 => GEMMA4_REPLY,
            Self::ChatMl => "<|im_end|>\n<|im_start|>assistant\n",
        }
    }
}

/// The long-lived chat context and what its KV cache currently holds, one slot per
/// position.
struct Session {
    ctx: LlamaContext<'static>,
    cached: Vec<Slot>,
}

/// One KV-cache position: a text token, or part of an image (identified by a hash
/// of its pixels, so the same screenshot in a later prompt is reused).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Slot {
    Token(LlamaToken),
    Image(u64),
}

/// An evaluated prompt: its slots and, when it contains an image, the multimodal
/// chunks that fill the `Slot::Image` span starting at `start`.
struct Plan {
    slots: Vec<Slot>,
    image: Option<(MtmdInputChunks, usize)>,
}

/// Prompt tokens evaluated per `decode` call (llama.cpp's default `n_batch` is larger).
const PREFILL_CHUNK: usize = 512;

impl Session {
    /// Makes the KV cache hold exactly `plan`, re-evaluating only the part after the
    /// prefix shared with what is cached (never splitting an image). Always evaluates
    /// at least the last slot so fresh logits are available. Returns slots reused.
    fn evaluate(&mut self, plan: &Plan, mtmd: Option<&mut MtmdContext>) -> EngineResult<usize> {
        let slots = &plan.slots;
        let mut keep = self
            .cached
            .iter()
            .zip(slots)
            .take_while(|(cached, new)| cached == new)
            .count()
            .min(slots.len().saturating_sub(1));
        // A partly matching image span is re-evaluated from its start.
        while keep > 0
            && matches!(slots.get(keep), Some(Slot::Image(_)))
            && slots[keep - 1] == slots[keep]
        {
            keep -= 1;
        }
        if keep < self.cached.len() {
            let from = u32::try_from(keep).map_err(runtime_error)?;
            if !self
                .ctx
                .clear_kv_cache_seq(Some(0), Some(from), None)
                .unwrap_or(false)
            {
                self.ctx.clear_kv_cache();
                keep = 0;
            }
            self.cached.truncate(keep);
        }
        let result = self.append(plan, keep, mtmd);
        if result.is_err() {
            self.reset();
        }
        result.map(|()| keep)
    }

    /// Evaluates `plan.slots[from..]` after the cached slots.
    fn append(
        &mut self,
        plan: &Plan,
        from: usize,
        mut mtmd: Option<&mut MtmdContext>,
    ) -> EngineResult<()> {
        let slots = &plan.slots;
        let mut index = from;
        while index < slots.len() {
            match slots[index] {
                Slot::Token(_) => {
                    let end = slots[index..]
                        .iter()
                        .position(|slot| matches!(slot, Slot::Image(_)))
                        .map_or(slots.len(), |offset| index + offset);
                    let tokens: Vec<LlamaToken> = slots[index..end]
                        .iter()
                        .filter_map(|slot| match slot {
                            Slot::Token(token) => Some(*token),
                            Slot::Image(_) => None,
                        })
                        .collect();
                    self.decode_tokens(&tokens, end == slots.len())?;
                    index = end;
                }
                Slot::Image(_) => {
                    let (chunks, start) = plan
                        .image
                        .as_ref()
                        .ok_or_else(|| runtime_error("image slots without image chunks"))?;
                    if index != *start {
                        return Err(runtime_error("image span reused only in part"));
                    }
                    let context = mtmd
                        .as_deref_mut()
                        .ok_or_else(|| runtime_error("image projector is unavailable"))?;
                    let n_past = i32::try_from(self.cached.len()).map_err(runtime_error)?;
                    let batch = i32::try_from(PREFILL_CHUNK).map_err(runtime_error)?;
                    let end = chunks
                        .eval_chunks(context, &mut self.ctx, n_past, 0, batch, false)
                        .map_err(runtime_error)?;
                    let span = usize::try_from(end - n_past).map_err(runtime_error)?;
                    let expected = slots[index..]
                        .iter()
                        .take_while(|slot| matches!(slot, Slot::Image(_)))
                        .count();
                    if span != expected {
                        return Err(runtime_error(format!(
                            "image used {span} positions, expected {expected}"
                        )));
                    }
                    self.cached.extend_from_slice(&slots[index..index + span]);
                    index += span;
                }
            }
        }
        Ok(())
    }

    /// Appends `tokens` after the cached slots; logits only for the final token,
    /// and only when `logits_last`.
    fn decode_tokens(&mut self, tokens: &[LlamaToken], logits_last: bool) -> EngineResult<()> {
        let chunks = tokens.chunks(PREFILL_CHUNK);
        let last_chunk = chunks.len().saturating_sub(1);
        for (index, chunk) in chunks.enumerate() {
            let mut batch = LlamaBatch::new(chunk.len(), 1);
            let base = i32::try_from(self.cached.len()).map_err(runtime_error)?;
            for (offset, token) in chunk.iter().enumerate() {
                let position = base + i32::try_from(offset).map_err(runtime_error)?;
                let logits = logits_last && index == last_chunk && offset + 1 == chunk.len();
                batch
                    .add(*token, position, &[0], logits)
                    .map_err(runtime_error)?;
            }
            self.ctx.decode(&mut batch).map_err(runtime_error)?;
            self.cached.extend(chunk.iter().copied().map(Slot::Token));
        }
        Ok(())
    }

    /// Forgets the cache; used when a decode failed and its state is unknown.
    fn reset(&mut self) {
        self.ctx.clear_kv_cache();
        self.cached.clear();
    }
}

impl LlamaChat {
    /// Loads a chat model, trying full GPU offload before CPU fallback.
    ///
    /// # Errors
    /// Returns [`EngineError::MissingModel`] for a missing file or a runtime error if loading fails.
    pub fn load(rt: &Runtime, path: &Path, projector: &Path) -> EngineResult<Self> {
        Self::load_with_gpu_layers(rt, path, projector, u32::MAX)
    }

    /// Loads another chat model whose turns use `format` (GPU first, CPU fallback).
    ///
    /// # Errors
    /// As [`LlamaChat::load`].
    pub fn load_with_format(
        rt: &Runtime,
        path: &Path,
        projector: &Path,
        format: PromptFormat,
    ) -> EngineResult<Self> {
        let mut chat = Self::load_with_gpu_layers(rt, path, projector, u32::MAX)?;
        chat.format = format;
        Ok(chat)
    }

    pub(crate) fn load_with_gpu_layers(
        rt: &Runtime,
        path: &Path,
        projector: &Path,
        layers: u32,
    ) -> EngineResult<Self> {
        let attempt = |gpu_layers| -> EngineResult<LlamaModel> {
            let model = load_model(rt, path, gpu_layers)?;
            let _ = context(
                &model,
                &rt.backend,
                CHAT_CONTEXT,
                false,
                LlamaPoolingType::Unspecified,
            )?;
            Ok(model)
        };
        let (model, device) = if layers == 0 {
            (attempt(0)?, "cpu")
        } else {
            match attempt(layers) {
                Ok(model) => (model, "gpu"),
                Err(error) => {
                    tracing::warn!(%error, "GPU chat model unavailable; retrying on CPU");
                    (attempt(0)?, "cpu")
                }
            }
        };
        tracing::info!(device, "loaded chat model");
        let model = Box::new(model);
        // SAFETY: the model is boxed, so its address is stable for the box's lifetime;
        // the box is never moved out of or replaced, and `LlamaChat` drops `session`
        // (the only holder of this reference) before `model`.
        let model_ref: &'static LlamaModel = unsafe { &*std::ptr::from_ref::<LlamaModel>(&model) };
        let ctx = context(
            model_ref,
            &rt.backend,
            CHAT_CONTEXT,
            false,
            LlamaPoolingType::Unspecified,
        )?;
        let mtmd = if projector.is_file() {
            let projector_path = projector.to_string_lossy();
            // A projector the GPU has no room for would abort the process (llama.cpp
            // asserts on a failed buffer allocation); it runs on the CPU instead.
            let room = file_bytes(projector).saturating_mul(3) / 2 + GPU_HEADROOM;
            let use_gpu = device == "gpu" && gpu_free_bytes().is_none_or(|free| free >= room);
            if device == "gpu" && !use_gpu {
                tracing::warn!("not enough GPU memory for the image projector; it runs on the CPU");
            }
            let params = MtmdContextParams {
                use_gpu,
                n_threads: threads(),
                print_timings: false,
                ..MtmdContextParams::default()
            };
            match MtmdContext::init_from_file(&projector_path, &model, &params) {
                Ok(mtmd) => Some(Mutex::new(mtmd)),
                Err(error) => {
                    tracing::warn!(%error, "multimodal projector unavailable; audio transcription disabled");
                    None
                }
            }
        } else {
            None
        };
        Ok(Self {
            session: Mutex::new(Session {
                ctx,
                cached: Vec::new(),
            }),
            mtmd,
            model,
            backend: Arc::clone(&rt.backend),
            device,
            format: PromptFormat::Gemma4,
        })
    }
    /// Reports whether the model is running with GPU or CPU placement.
    pub fn device(&self) -> &'static str {
        self.device
    }
    /// Reports whether the loaded projector supports 16 kHz audio input.
    pub fn supports_audio(&self) -> bool {
        self.mtmd.as_ref().is_some_and(|mtmd| {
            mtmd.lock().is_ok_and(|mtmd| {
                mtmd.support_audio() && mtmd.get_audio_sample_rate() == Some(16_000)
            })
        })
    }
    /// Reports whether the loaded projector can read images.
    pub fn supports_vision(&self) -> bool {
        self.mtmd
            .as_ref()
            .is_some_and(|mtmd| mtmd.lock().is_ok_and(|mtmd| mtmd.support_vision()))
    }

    /// Formats the request in the model's turn format and tokenizes it (and its image),
    /// checking the context budget.
    fn plan(&self, request: &ChatRequest<'_>) -> EngineResult<Plan> {
        let vocab = self.model.vocab();
        let plan = match request.image {
            None => {
                let prompt = self.format.prefix(request.system, request.user) + self.format.reply();
                let slots = vocab
                    .tokenize(prompt.as_bytes(), true, true)
                    .into_iter()
                    .map(Slot::Token)
                    .collect();
                Plan { slots, image: None }
            }
            Some(part) => {
                let mtmd = self
                    .mtmd
                    .as_ref()
                    .ok_or_else(|| runtime_error("image projector is unavailable"))?
                    .lock()
                    .map_err(runtime_error)?;
                let prefix = self.format.prefix(request.system, request.user);
                let mut slots: Vec<Slot> = vocab
                    .tokenize(prefix.as_bytes(), true, true)
                    .into_iter()
                    .map(Slot::Token)
                    .collect();
                let bitmap = MtmdBitmap::from_image_data(
                    part.image.width,
                    part.image.height,
                    &part.image.rgb,
                )
                .map_err(runtime_error)?;
                let chunks = mtmd
                    .tokenize(
                        MtmdInputText {
                            text: mtmd_default_marker().to_owned(),
                            add_special: false,
                            parse_special: true,
                        },
                        &[&bitmap],
                    )
                    .map_err(runtime_error)?;
                let positions = usize::try_from(chunks.total_positions()).map_err(runtime_error)?;
                let start = slots.len();
                slots.extend(std::iter::repeat_n(
                    Slot::Image(image_key(part.image)),
                    positions,
                ));
                let suffix = format!("{}{}", part.text_after, self.format.reply());
                slots.extend(
                    vocab
                        .tokenize(suffix.as_bytes(), false, true)
                        .into_iter()
                        .map(Slot::Token),
                );
                Plan {
                    slots,
                    image: Some((chunks, start)),
                }
            }
        };
        let total = plan.slots.len().saturating_add(request.max_tokens as usize);
        if total > CHAT_CONTEXT as usize {
            return Err(EngineError::TooLong {
                tokens: total,
                limit: CHAT_CONTEXT as usize,
            });
        }
        if plan.slots.is_empty() {
            return Err(runtime_error("chat prompt tokenized to empty input"));
        }
        Ok(plan)
    }

    /// Evaluates `plan` into the session (locking the projector only when the
    /// image is not already cached).
    fn evaluate(&self, session: &mut Session, plan: &Plan) -> EngineResult<usize> {
        let mut guard = match (&plan.image, &self.mtmd) {
            (Some(_), Some(mtmd)) => Some(mtmd.lock().map_err(runtime_error)?),
            _ => None,
        };
        session.evaluate(plan, guard.as_deref_mut())
    }

    fn sampler(&self, grammar: Option<&str>) -> EngineResult<Sampling> {
        let Some(grammar) = grammar else {
            return Ok(Sampling::Free(LlamaSampler::chain_simple([
                LlamaSampler::temp(0.2),
                LlamaSampler::dist(0),
            ])));
        };
        LlamaSampler::grammar(&self.model, grammar, "root")
            .map(Sampling::Constrained)
            .map_err(runtime_error)
    }
}

/// How the next token is chosen.
enum Sampling {
    /// Low-temperature sampling for free text.
    Free(LlamaSampler),
    /// Greedy within a GBNF grammar (element ids, points).
    Constrained(LlamaSampler),
}

impl Sampling {
    /// Picks and accepts the next token from the last evaluated position.
    ///
    /// # Errors
    /// The grammar allows no token at all.
    fn next(&mut self, ctx: &LlamaContext<'_>) -> EngineResult<LlamaToken> {
        match self {
            Self::Free(sampler) => Ok(sampler.sample(ctx, -1)),
            Self::Constrained(grammar) => {
                let token = constrained_greedy(grammar, ctx.get_logits_ith(-1))
                    .ok_or_else(|| runtime_error("the reply grammar allows no token here"))?;
                grammar.accept(token);
                Ok(token)
            }
        }
    }
}

/// Candidates checked against the grammar at once when the model's own best token
/// is not allowed.
const GRAMMAR_SHORTLIST: usize = 256;

/// The highest-scoring token the grammar allows: the choice of running the grammar
/// over every candidate and then picking greedily (only ties at the shortlist's
/// lowest score may break differently), without matching all ~262k vocabulary
/// entries against the grammar on every step (seconds per reply on a laptop CPU).
/// The model's best token is checked first, then its top [`GRAMMAR_SHORTLIST`]; the
/// best allowed token there is the best allowed overall. The whole vocabulary is
/// checked only when none of those is allowed. `None` when the grammar allows nothing.
fn constrained_greedy(grammar: &mut LlamaSampler, logits: &[f32]) -> Option<LlamaToken> {
    let best = argmax(logits.iter().copied().enumerate());
    if let Some(token) = best_allowed(grammar, logits, &[best]) {
        return Some(token);
    }
    let mut order: Vec<usize> = (0..logits.len()).collect();
    let shortlist = GRAMMAR_SHORTLIST.min(order.len());
    if shortlist > 0 && shortlist < order.len() {
        order.select_nth_unstable_by(shortlist - 1, |a, b| logits[*b].total_cmp(&logits[*a]));
    }
    best_allowed(grammar, logits, &order[..shortlist])
        .or_else(|| best_allowed(grammar, logits, &order[shortlist..]))
}

/// The highest-scoring of `indices` that the grammar allows, if any.
fn best_allowed(grammar: &mut LlamaSampler, logits: &[f32], indices: &[usize]) -> Option<LlamaToken> {
    if indices.is_empty() {
        return None;
    }
    let mut shortlist = LlamaTokenDataArray::new(
        indices.iter().map(|&i| candidate(i, logits[i])).collect(),
        false,
    );
    grammar.apply(&mut shortlist);
    shortlist
        .data
        .iter()
        .filter(|c| c.logit() > f32::NEG_INFINITY)
        .map(|c| (index_of(c.id()), c.logit()))
        .reduce(|a, b| if b.1 > a.1 || (b.1 == a.1 && b.0 < a.0) { b } else { a })
        .map(|(i, _)| token_at(i))
}

/// Index of the largest score; the first one on ties, like llama.cpp's greedy sampler.
fn argmax(scores: impl Iterator<Item = (usize, f32)>) -> usize {
    scores
        .fold(None, |best: Option<(usize, f32)>, (i, score)| match best {
            Some((_, top)) if top >= score => best,
            _ => Some((i, score)),
        })
        .map_or(0, |(i, _)| i)
}

fn candidate(index: usize, logit: f32) -> LlamaTokenData {
    LlamaTokenData::new(token_at(index), logit, 0.0)
}

fn token_at(index: usize) -> LlamaToken {
    LlamaToken::new(i32::try_from(index).unwrap_or(i32::MAX))
}

fn index_of(token: LlamaToken) -> usize {
    usize::try_from(token.0).unwrap_or(0)
}

/// Hash of an image's size and pixels; equal screenshots share KV-cache slots.
fn image_key(image: &RgbImage) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    (image.width, image.height).hash(&mut hasher);
    image.rgb.hash(&mut hasher);
    hasher.finish()
}

/// End of the user turn and start of the model's reply.
const GEMMA4_REPLY: &str = "<turn|>\n<|turn>model\n";

/// Gemma 4's turn format (the GGUF's Jinja template, which llama.cpp's built-in
/// template detection does not recognise) up to the end of the user's text.
/// BOS is added by the tokenizer; no thinking.
fn gemma4_prefix(system: Option<&str>, user: &str) -> String {
    let mut prompt = String::with_capacity(system.map_or(0, str::len) + user.len() + 64);
    if let Some(system) = system {
        prompt.push_str("<|turn>system\n");
        prompt.push_str(system);
        prompt.push_str("<turn|>\n");
    }
    prompt.push_str("<|turn>user\n");
    prompt.push_str(user);
    prompt
}

/// A whole Gemma 4 prompt, ending where the model's reply starts.
fn gemma4_prompt(system: Option<&str>, user: &str) -> String {
    gemma4_prefix(system, user) + GEMMA4_REPLY
}

impl ChatModel for LlamaChat {
    fn generate(
        &self,
        request: &ChatRequest<'_>,
        on_text: &mut dyn FnMut(&str) -> Flow,
    ) -> EngineResult<GenerationStats> {
        let start = Instant::now();
        let plan = self.plan(request)?;
        let mut sampler = self.sampler(request.grammar)?;
        let mut session = self.session.lock().map_err(runtime_error)?;
        let reused = self.evaluate(&mut session, &plan)?;
        // Decoding is asynchronous on the GPU; its time shows up in `first_token_ms`.
        tracing::debug!(
            prompt_slots = plan.slots.len(),
            reused,
            image = plan.image.is_some(),
            "chat prompt queued"
        );
        let vocab = self.model.vocab();
        let mut stats = GenerationStats {
            prompt_tokens: u32::try_from(plan.slots.len()).unwrap_or(u32::MAX),
            ..GenerationStats::default()
        };
        let mut raw = Vec::with_capacity(8);
        let mut pending = Vec::with_capacity(4);
        for index in 0..request.max_tokens {
            // Also accepts the token into the sampler (grammar state).
            let token = sampler.next(&session.ctx)?;
            stats.generated_tokens = index.saturating_add(1);
            if vocab.is_eog(token) {
                break;
            }
            let valid = token_text_piece(&vocab, token, &mut raw, &mut pending)?;
            if valid > 0 {
                let text = std::str::from_utf8(&pending[..valid]).map_err(runtime_error)?;
                if stats.first_token_ms == 0 {
                    stats.first_token_ms =
                        u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
                }
                let stop = on_text(text) == Flow::Stop;
                pending.drain(..valid);
                if stop {
                    break;
                }
            }
            if index + 1 < request.max_tokens {
                let decoded = session.decode_tokens(&[token], true);
                if decoded.is_err() {
                    session.reset();
                }
                decoded?;
            }
        }
        if !pending.is_empty() {
            let text = String::from_utf8_lossy(&pending);
            if !text.is_empty() {
                if stats.first_token_ms == 0 {
                    stats.first_token_ms =
                        u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
                }
                let _ = on_text(&text);
            }
        }
        stats.total_ms = u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
        Ok(stats)
    }

    fn prefill(&self, request: &ChatRequest<'_>) -> EngineResult<()> {
        let start = Instant::now();
        let plan = self.plan(request)?;
        let mut session = self.session.lock().map_err(runtime_error)?;
        let reused = self.evaluate(&mut session, &plan)?;
        // Wait for the GPU so the time below is real and the work is done before the
        // question arrives.
        session.ctx.synchronize();
        tracing::debug!(
            prompt_slots = plan.slots.len(),
            reused,
            prefill_ms = start.elapsed().as_millis(),
            "chat prompt prefilled"
        );
        Ok(())
    }
}

impl Transcriber for LlamaChat {
    fn transcribe(&self, pcm: &[f32], _hint: &str) -> EngineResult<String> {
        if pcm.len() < 4_800 {
            return Ok(String::new());
        }
        if pcm.len() > 30 * 16_000 {
            return Err(EngineError::TooLong {
                tokens: pcm.len(),
                limit: 30 * 16_000,
            });
        }
        let start = Instant::now();
        let audio_seconds = pcm.len() as f64 / 16_000.0;
        let model = &*self.model;
        let mut mtmd = self
            .mtmd
            .as_ref()
            .ok_or_else(|| runtime_error("audio projector is unavailable"))?
            .lock()
            .map_err(runtime_error)?;
        if !mtmd.support_audio() || mtmd.get_audio_sample_rate() != Some(16_000) {
            return Err(runtime_error("projector does not support 16 kHz audio"));
        }
        let bitmap = MtmdBitmap::from_audio_data(pcm).map_err(runtime_error)?;
        let instruction =
            "Transcribe this English audio exactly as spoken. Output only the transcript.";
        let prompt = gemma4_prompt(None, &format!("{}{instruction}", mtmd_default_marker()));
        let chunks = mtmd
            .tokenize(
                MtmdInputText {
                    text: prompt,
                    add_special: true,
                    parse_special: true,
                },
                &[&bitmap],
            )
            .map_err(runtime_error)?;
        let mut ctx = context(
            model,
            &self.backend,
            TRANSCRIBE_CONTEXT,
            false,
            LlamaPoolingType::Unspecified,
        )?;
        let n_past = chunks
            .eval_chunks(&mut mtmd, &mut ctx, 0, 0, 512, true)
            .map_err(runtime_error)?;
        let vocab = model.vocab();
        let mut sampler = LlamaSampler::greedy();
        let mut raw = Vec::with_capacity(8);
        let mut pending = Vec::with_capacity(4);
        let mut transcript = String::with_capacity(128);
        let mut batch = LlamaBatch::new(1, 1);
        for index in 0..96_i32 {
            let token = sampler.sample(&ctx, -1);
            if vocab.is_eog(token) {
                break;
            }
            let valid = token_text_piece(&vocab, token, &mut raw, &mut pending)?;
            if valid > 0 {
                let text = std::str::from_utf8(&pending[..valid]).map_err(runtime_error)?;
                transcript.push_str(text);
                pending.drain(..valid);
            }
            if index < 95 {
                batch.clear();
                batch
                    .add(token, n_past + index, &[0], true)
                    .map_err(runtime_error)?;
                ctx.decode(&mut batch).map_err(runtime_error)?;
            }
        }
        if !pending.is_empty() {
            transcript.push_str(&String::from_utf8_lossy(&pending));
        }
        tracing::debug!(
            duration_ms = u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX),
            audio_seconds,
            "audio transcription completed"
        );
        Ok(strip_surrounding_quotes(&transcript).to_owned())
    }
}

/// A model loaded on first use, then kept: dropping one did not return its memory
/// (llama.cpp keeps the allocation) and reloading costs every use its load time.
/// The embedding model (only agents with documents search) and the tier-3 grounder
/// (only screens without readable elements) wait here until needed.
pub struct OnDemand<T> {
    load: Box<dyn Fn() -> EngineResult<T> + Send + Sync>,
    what: &'static str,
    loaded: std::sync::OnceLock<T>,
    /// Serializes the first load so two callers do not both load.
    loading: Mutex<()>,
    check: Option<Box<dyn Fn() -> bool + Send + Sync>>,
}

impl<T> OnDemand<T> {
    /// Checks `files` exist; loads nothing until [`OnDemand::get`]. `what` names the
    /// model in logs.
    ///
    /// # Errors
    /// [`EngineError::MissingModel`] for the first missing file.
    pub fn new(
        what: &'static str,
        files: &[&Path],
        load: impl Fn() -> EngineResult<T> + Send + Sync + 'static,
    ) -> EngineResult<Self> {
        if let Some(missing) = files.iter().find(|path| !path.is_file()) {
            return Err(EngineError::MissingModel(missing.display().to_string()));
        }
        Ok(Self {
            load: Box::new(load),
            what,
            loaded: std::sync::OnceLock::new(),
            loading: Mutex::new(()),
            check: None,
        })
    }

    /// The model, loading it now on first use.
    ///
    /// # Errors
    /// The load failed (it is tried again on the next call).
    pub fn get(&self) -> EngineResult<&T> {
        if let Some(model) = self.loaded.get() {
            return Ok(model);
        }
        let _guard = self.loading.lock().map_err(runtime_error)?;
        if let Some(model) = self.loaded.get() {
            return Ok(model);
        }
        let started = std::time::Instant::now();
        let model = (self.load)()?;
        tracing::info!(
            model = self.what,
            elapsed_ms = started.elapsed().as_millis(),
            "model loaded on demand"
        );
        Ok(self.loaded.get_or_init(|| model))
    }

    /// Whether the model is in memory.
    pub fn is_loaded(&self) -> bool {
        self.loaded.get().is_some()
    }

    /// Whether loading would be attempted now (see [`OnDemand::with_check`]).
    pub fn can_load(&self) -> bool {
        self.check.as_ref().is_none_or(|check| check())
    }

    /// Adds a check that must pass before loading (e.g. free GPU memory).
    #[must_use]
    pub fn with_check(mut self, check: impl Fn() -> bool + Send + Sync + 'static) -> Self {
        self.check = Some(Box::new(check));
        self
    }
}

impl OnDemand<LlamaEmbedder> {
    /// The embedding model at `path`, loaded on the first search.
    ///
    /// # Errors
    /// [`EngineError::MissingModel`] when the file is missing.
    pub fn embedder(rt: &Runtime, path: &Path) -> EngineResult<Self> {
        let (rt, owned) = (rt.clone(), path.to_owned());
        Self::new("embedding", &[path], move || {
            LlamaEmbedder::load(&rt, &owned)
        })
    }
}

impl Embedder for OnDemand<LlamaEmbedder> {
    fn embed_documents(&self, texts: &[&str]) -> EngineResult<Vec<Vec<f32>>> {
        self.get()?.embed_documents(texts)
    }

    fn embed_query(&self, text: &str) -> EngineResult<Vec<f32>> {
        self.get()?.embed_query(text)
    }
}

/// bge-small-en-v1.5 (MIT, CLS pooling, 384 dims) normalized vector generator.
pub struct LlamaEmbedder {
    backend: Arc<LlamaBackend>,
    model: Mutex<LlamaModel>,
    device: &'static str,
}
impl LlamaEmbedder {
    /// Loads the embedding model with CLS pooling and CPU fallback.
    ///
    /// # Errors
    /// Returns [`EngineError::MissingModel`] for a missing file or a runtime error if loading fails.
    pub fn load(rt: &Runtime, path: &Path) -> EngineResult<Self> {
        Self::load_with_gpu_layers(rt, path, u32::MAX)
    }
    pub(crate) fn load_with_gpu_layers(
        rt: &Runtime,
        path: &Path,
        layers: u32,
    ) -> EngineResult<Self> {
        let attempt = |gpu_layers| -> EngineResult<LlamaModel> {
            let model = load_model(rt, path, gpu_layers)?;
            let _ = context(
                &model,
                &rt.backend,
                EMBED_CONTEXT,
                true,
                LlamaPoolingType::Cls,
            )?;
            Ok(model)
        };
        if layers == 0 {
            let model = attempt(0)?;
            tracing::info!(device = "cpu", "loaded embedding model");
            return Ok(Self {
                backend: Arc::clone(&rt.backend),
                model: Mutex::new(model),
                device: "cpu",
            });
        }
        match attempt(layers) {
            Ok(model) => {
                tracing::info!(device = "gpu", "loaded embedding model");
                Ok(Self {
                    backend: Arc::clone(&rt.backend),
                    model: Mutex::new(model),
                    device: "gpu",
                })
            }
            Err(error) => {
                tracing::warn!(%error, "GPU embedding model unavailable; retrying on CPU");
                let model = attempt(0)?;
                tracing::info!(device = "cpu", "loaded embedding model");
                Ok(Self {
                    backend: Arc::clone(&rt.backend),
                    model: Mutex::new(model),
                    device: "cpu",
                })
            }
        }
    }
    /// Reports whether the model is running with GPU or CPU placement.
    pub fn device(&self) -> &'static str {
        self.device
    }
    fn embed(&self, text: &str, prefix: &str) -> EngineResult<Vec<f32>> {
        let model = self.model.lock().map_err(runtime_error)?;
        let mut ctx = context(
            &model,
            &self.backend,
            EMBED_CONTEXT,
            true,
            LlamaPoolingType::Cls,
        )?;
        let input = format!("{prefix}{text}");
        let vocab = model.vocab();
        let mut tokens = vocab.tokenize(input.as_bytes(), true, true);
        // Chunks aim at 400 tokens (+60 overlap) by a different count; the model
        // reads 512, so the rare longer chunk is embedded by its first 512 tokens.
        tokens.truncate(EMBED_CONTEXT as usize);
        if tokens.is_empty() {
            return Err(runtime_error("embedding input tokenized to empty input"));
        }
        let mut batch = LlamaBatch::new(tokens.len(), 1);
        batch
            .add_sequence(&tokens, 0, false)
            .map_err(runtime_error)?;
        ctx.decode(&mut batch).map_err(runtime_error)?;
        let vector = ctx.embeddings_seq_ith(0).map_err(runtime_error)?;
        if vector.len() < EMBEDDING_DIM {
            return Err(runtime_error(format!(
                "embedding has {} dimensions, expected at least {EMBEDDING_DIM}",
                vector.len()
            )));
        }
        let mut result = vector[..EMBEDDING_DIM].to_vec();
        let norm = result.iter().map(|value| value * value).sum::<f32>().sqrt();
        if norm.is_finite() && norm > f32::EPSILON {
            for value in &mut result {
                *value /= norm;
            }
        } else {
            return Err(runtime_error("embedding has zero or non-finite norm"));
        }
        Ok(result)
    }
}
impl Embedder for LlamaEmbedder {
    fn embed_documents(&self, texts: &[&str]) -> EngineResult<Vec<Vec<f32>>> {
        let mut result = Vec::with_capacity(texts.len());
        for text in texts {
            result.push(self.embed(text, "")?);
        }
        Ok(result)
    }
    fn embed_query(&self, text: &str) -> EngineResult<Vec<f32>> {
        self.embed(
            text,
            "Represent this sentence for searching relevant passages: ",
        )
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn argmax_takes_the_first_of_equal_scores() {
        let scores = [1.0, 3.0, 3.0, f32::NEG_INFINITY];
        assert_eq!(super::argmax(scores.iter().copied().enumerate()), 1);
        assert_eq!(super::argmax(std::iter::empty()), 0);
        assert_eq!(super::argmax([(7, f32::NEG_INFINITY), (9, -1.0)].into_iter()), 9);
    }

    use super::*;
    use crate::engine::ImagePart;
    use std::path::PathBuf;
    fn model_path(file: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("models")
            .join(file)
    }
    #[test]
    #[ignore = "needs model files"]
    fn chat_streams_answer_and_stats() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat model loads");
        let request = ChatRequest {
            system: "Reply with exactly the word OK",
            user: "Reply with exactly the word OK",
            max_tokens: 32,
            grammar: None,
            image: None,
        };
        let mut answer = String::new();
        let stats = model
            .generate(&request, &mut |piece| {
                answer.push_str(piece);
                Flow::Continue
            })
            .expect("generation succeeds");
        assert!(answer.contains("OK"));
        assert!(stats.generated_tokens > 0);
        assert!(stats.first_token_ms <= stats.total_ms);
    }
    #[test]
    #[ignore = "needs model files"]
    fn reused_prefix_picks_the_same_choice_as_a_cold_prompt() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat model loads");
        let screen = "Screen:\ne1 | button | Save\ne2 | cell | Q1, Juan Dela Cruz\ne3 | cell | Q1, Ana Santos\n\n";
        let choices = ["e1", "e2", "e3", "none"].map(String::from);
        let grammar = crate::prompt::choices_grammar(&choices);
        let pick = |user: &str| {
            let mut reply = String::new();
            let request = ChatRequest {
                system: "Pick the element id where the user should act.",
                user,
                max_tokens: 8,
                grammar: Some(&grammar),
                image: None,
            };
            model
                .generate(&request, &mut |piece| {
                    reply.push_str(piece);
                    Flow::Continue
                })
                .expect("choice generation succeeds");
            reply
        };
        let question = format!("{screen}Question: Where do I type Juan's first quarter grade?");
        model.session.lock().expect("session").reset();
        let cold = pick(&question);
        // Same prefix, different suffix, then the question again: mostly reused cache.
        let _ = pick(&format!("{screen}Question: Where is the save button?"));
        let warm = pick(&question);
        assert!(
            choices.contains(&cold),
            "reply {cold:?} is one of the choices"
        );
        assert_eq!(cold, warm);
        assert_eq!(cold, "e2");
    }
    /// 640x400 white "screen" with a red square (x 400..480, y 240..320) and a
    /// blue square (x 80..160, y 60..140).
    fn two_squares() -> RgbImage {
        let (width, height) = (640u32, 400u32);
        let mut rgb = Vec::with_capacity((width * height * 3) as usize);
        for y in 0..height {
            for x in 0..width {
                let pixel = if (400..480).contains(&x) && (240..320).contains(&y) {
                    [220, 20, 20]
                } else if (80..160).contains(&x) && (60..140).contains(&y) {
                    [20, 40, 220]
                } else {
                    [255, 255, 255]
                };
                rgb.extend_from_slice(&pixel);
            }
        }
        RgbImage { width, height, rgb }
    }
    #[test]
    #[ignore = "needs model files"]
    fn vision_points_at_the_asked_object_and_reuses_the_image_prefix() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat model loads");
        assert!(model.supports_vision());
        let shot = crate::screenshot::Prepared {
            image: two_squares(),
            monitor: crate::model::MonitorFrame {
                x: 0,
                y: 0,
                width: 640,
                height: 400,
                scale_factor: 1.0,
            },
            origin: (0.0, 0.0),
            scale: 1.0,
        };
        let ask = |question: &str, task: &str, grammar: &str| {
            let mut reply = String::new();
            model
                .generate(
                    &ChatRequest {
                        system: "You locate things on a screenshot.",
                        user: &format!("Question: {question}\n\n"),
                        max_tokens: 12,
                        grammar: Some(grammar),
                        image: Some(ImagePart {
                            image: &shot.image,
                            text_after: task,
                        }),
                    },
                    &mut |piece| {
                        reply.push_str(piece);
                        Flow::Continue
                    },
                )
                .expect("image generation succeeds");
            reply
        };
        let point_task =
            crate::prompt::TurnPrompt::target_task(crate::model::ScreenMode::ImageOnly);
        // Square bounds (x, y ranges) widened by a 40 px margin. The blue question comes
        // first so the red one below is encoded from scratch.
        let mut cold_ms = 0;
        for (question, xs, ys) in [
            ("Where is the blue square?", 40.0..200.0, 20.0..180.0),
            ("Where is the red square?", 360.0..520.0, 200.0..360.0),
        ] {
            let started = std::time::Instant::now();
            let reply = ask(question, &point_task, crate::screenshot::POINT_GRAMMAR);
            cold_ms = started.elapsed().as_millis();
            let (x, y) = crate::screenshot::parse_point(&shot, &reply).expect("point reply");
            eprintln!("{question} {reply:?} -> ({x:.0}, {y:.0}) in {cold_ms} ms");
            assert!(xs.contains(&x) && ys.contains(&y), "{question} {reply}");
        }
        // Same question and image, different task: the image is not encoded again.
        let started = std::time::Instant::now();
        let pick = ask(
            "Where is the red square?",
            "Reply with left if the red square is on the left half of the screenshot, else right.",
            &crate::prompt::choices_grammar(&["left".into(), "right".into()]),
        );
        let warm_ms = started.elapsed().as_millis();
        eprintln!("pick {pick:?} in {warm_ms} ms");
        assert_eq!(pick, "right");
        assert!(warm_ms < cold_ms, "warm {warm_ms} ms vs cold {cold_ms} ms");
    }
    #[test]
    #[ignore = "needs model files"]
    fn embeddings_are_normalized_and_rank_relevant_passage_higher() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaEmbedder::load(&rt, &model_path(super::super::EMBEDDING_MODEL_FILE))
            .expect("embedding model loads");
        let docs = model
            .embed_documents(&[
                "Grading assignments requires assessing student work against a rubric.",
                "Cooking pasta requires boiling water and adding salt.",
            ])
            .expect("documents embed");
        let query = model
            .embed_query("How should I grade student assignments?")
            .expect("query embeds");
        assert_eq!(query.len(), super::super::EMBEDDING_DIM);
        let norm = query.iter().map(|v| v * v).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-4);
        let cosine = |a: &[f32], b: &[f32]| a.iter().zip(b).map(|(x, y)| x * y).sum::<f32>();
        assert!(cosine(&query, &docs[0]) > cosine(&query, &docs[1]));
    }
    #[test]
    #[ignore = "needs model files"]
    fn embedder_loads_on_first_search() {
        let rt = Runtime::init().expect("runtime initializes");
        let path = model_path(super::super::EMBEDDING_MODEL_FILE);
        let lazy = OnDemand::embedder(&rt, &path).expect("file exists");
        assert!(!lazy.is_loaded(), "nothing loads before the first search");
        let question = "How should I grade student assignments?";
        let first = lazy.embed_query(question).expect("query embeds");
        assert!(lazy.is_loaded());
        let eager = LlamaEmbedder::load(&rt, &path).expect("embedding model loads");
        assert_eq!(first, eager.embed_query(question).expect("query embeds"));
        assert!(OnDemand::embedder(&rt, &model_path("missing.gguf")).is_err());
    }
    #[test]
    #[ignore = "needs model files"]
    fn forced_cpu_model_loads() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load_with_gpu_layers(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
            0,
        )
        .expect("CPU model loads");
        assert_eq!(model.device(), "cpu");
    }

    #[test]
    fn surrounding_quotes_are_removed() {
        assert_eq!(strip_surrounding_quotes("  \"hello\"  "), "hello");
        assert_eq!(strip_surrounding_quotes("‘hello’"), "hello");
        assert_eq!(strip_surrounding_quotes("hello"), "hello");
    }

    #[test]
    #[ignore = "needs model files"]
    fn gemma_audio_load_and_sine_transcription() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat and projector load");
        assert!(model.supports_audio());
        let pcm = (0..16_000)
            .map(|sample| (std::f32::consts::TAU * 440.0 * sample as f32 / 16_000.0).sin())
            .collect::<Vec<_>>();
        assert!(model.transcribe(&pcm, "").is_ok());
    }

    #[test]
    #[ignore = "needs model files"]
    fn gemma_transcribes_optional_grade_fixture() {
        let wav_path = std::path::Path::new("/tmp/q_en.wav");
        if !wav_path.is_file() {
            return;
        }
        let bytes = std::fs::read(wav_path).expect("WAV fixture reads");
        assert!(bytes.len() >= 44);
        assert_eq!(&bytes[..4], b"RIFF");
        assert_eq!(&bytes[8..12], b"WAVE");
        // `say` writes extra chunks before `fmt `, so locate it instead of assuming offset 12.
        let fmt = bytes
            .windows(4)
            .position(|window| window == b"fmt ")
            .expect("WAV fmt chunk exists")
            + 8;
        let u16_at = |at: usize| u16::from_le_bytes([bytes[at], bytes[at + 1]]);
        assert_eq!(u16_at(fmt), 1, "PCM");
        assert_eq!(u16_at(fmt + 2), 1, "mono");
        assert_eq!(
            u32::from_le_bytes([
                bytes[fmt + 4],
                bytes[fmt + 5],
                bytes[fmt + 6],
                bytes[fmt + 7]
            ]),
            16_000
        );
        assert_eq!(u16_at(fmt + 14), 16, "16-bit");
        let data_offset = bytes
            .windows(4)
            .position(|window| window == b"data")
            .map(|position| position + 8)
            .expect("WAV data chunk exists");
        let pcm = bytes[data_offset..]
            .as_chunks::<2>()
            .0
            .iter()
            .map(|sample| f32::from(i16::from_le_bytes([sample[0], sample[1]])) / 32_768.0)
            .collect::<Vec<_>>();
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat and projector load");
        assert!(model.supports_audio());
        let transcript = model.transcribe(&pcm, "").expect("speech transcribes");
        assert!(transcript.to_lowercase().contains("grade"));
    }
}
