//! In-process llama.cpp runtime for local chat and embeddings.
use std::{
    path::Path,
    sync::{Arc, LazyLock, Mutex},
    time::Instant,
};

use super::{
    ChatModel, ChatRequest, EMBEDDING_DIM, Embedder, EngineError, EngineResult, Flow,
    GenerationStats, Transcriber,
};
use crate::model::Language;
use llama_cpp_2::{
    LogOptions,
    context::{
        LlamaContext,
        params::{LlamaContextParams, LlamaPoolingType},
    },
    llama_backend::LlamaBackend,
    llama_batch::LlamaBatch,
    model::{LlamaModel, params::LlamaModelParams},
    mtmd::{MtmdBitmap, MtmdContext, MtmdContextParams, MtmdInputText, mtmd_default_marker},
    sampling::LlamaSampler,
    send_logs_to_tracing,
    token::LlamaToken,
};
fn token_text_piece(
    vocab: &llama_cpp_2::vocab::LlamaVocab<'_>,
    token: llama_cpp_2::token::LlamaToken,
    raw: &mut Vec<u8>,
    pending: &mut Vec<u8>,
) -> EngineResult<usize> {
    raw.clear();
    vocab.token_to_piece_into(token, raw, false, None);
    pending.extend_from_slice(raw);
    match std::str::from_utf8(pending) {
        Ok(text) => Ok(text.len()),
        Err(error) if error.error_len().is_none() => Ok(error.valid_up_to()),
        Err(error) => Err(runtime_error(format!(
            "invalid UTF-8 generated by model: {error}"
        ))),
    }
}

fn strip_surrounding_quotes(text: &str) -> &str {
    let trimmed = text.trim();
    for (opening, closing) in [('"', '"'), ('\'', '\''), ('“', '”'), ('‘', '’')] {
        if trimmed.starts_with(opening) && trimmed.ends_with(closing) && trimmed.len() >= 2 {
            return trimmed[opening.len_utf8()..trimmed.len() - closing.len_utf8()].trim();
        }
    }
    trimmed
}

static BACKEND: LazyLock<Result<Arc<LlamaBackend>, String>> = LazyLock::new(|| {
    LlamaBackend::init()
        .map(Arc::new)
        .map_err(|error| error.to_string())
});
const CHAT_CONTEXT: u32 = 4096;
const EMBED_CONTEXT: u32 = 2048;

/// Initialized llama.cpp backend shared by all loaded models.
pub struct Runtime {
    backend: Arc<LlamaBackend>,
}

impl Runtime {
    /// Initializes llama.cpp and routes its logs through tracing.
    ///
    /// # Errors
    /// Returns a runtime error if the backend cannot be initialized.
    pub fn init() -> EngineResult<Self> {
        send_logs_to_tracing(LogOptions::default());
        let backend = BACKEND
            .as_ref()
            .map_err(|error| EngineError::Runtime(error.clone()))?;
        Ok(Self {
            backend: Arc::clone(backend),
        })
    }
}

fn runtime_error(error: impl std::fmt::Display) -> EngineError {
    EngineError::Runtime(error.to_string())
}
fn threads() -> i32 {
    std::thread::available_parallelism().map_or(1, |n| i32::try_from(n.get()).unwrap_or(i32::MAX))
}

fn load_model(rt: &Runtime, path: &Path, layers: u32) -> EngineResult<LlamaModel> {
    if !path.is_file() {
        return Err(EngineError::MissingModel(path.display().to_string()));
    }
    LlamaModel::load_from_file(
        &rt.backend,
        path,
        &LlamaModelParams::default().with_n_gpu_layers(layers),
    )
    .map_err(runtime_error)
}
fn context<'a>(
    model: &'a LlamaModel,
    backend: &LlamaBackend,
    size: u32,
    embeddings: bool,
    pooling: LlamaPoolingType,
) -> EngineResult<LlamaContext<'a>> {
    let n_ctx = std::num::NonZeroU32::new(size);
    let params = LlamaContextParams::default()
        .with_n_ctx(n_ctx)
        .with_n_threads(threads())
        .with_n_threads_batch(threads())
        .with_embeddings(embeddings)
        .with_pooling_type(pooling);
    model.new_context(backend, params).map_err(runtime_error)
}

/// Chat model loaded from a GGUF file.
///
/// `session` and `mtmd` hold pointers into `model`; they are declared first so
/// Rust drops them before it.
pub struct LlamaChat {
    session: Mutex<Session>,
    mtmd: Option<Mutex<MtmdContext>>,
    model: Box<LlamaModel>,
    backend: Arc<LlamaBackend>,
    device: &'static str,
}

/// The long-lived chat context and the tokens its KV cache currently holds.
struct Session {
    ctx: LlamaContext<'static>,
    cached: Vec<LlamaToken>,
}

/// Prompt tokens evaluated per `decode` call (llama.cpp's default `n_batch` is larger).
const PREFILL_CHUNK: usize = 512;

impl Session {
    /// Makes the KV cache hold exactly `tokens`, re-evaluating only the part after
    /// the prefix shared with what is cached. Always evaluates at least the last
    /// token so fresh logits are available. Returns how many tokens were reused.
    fn evaluate(&mut self, tokens: &[LlamaToken]) -> EngineResult<usize> {
        let shared = self
            .cached
            .iter()
            .zip(tokens)
            .take_while(|(cached, new)| cached == new)
            .count();
        let mut keep = shared.min(tokens.len().saturating_sub(1));
        if keep < self.cached.len() {
            let from = u32::try_from(keep).map_err(runtime_error)?;
            if !self
                .ctx
                .clear_kv_cache_seq(Some(0), Some(from), None)
                .unwrap_or(false)
            {
                self.ctx.clear_kv_cache();
                keep = 0;
            }
            self.cached.truncate(keep);
        }
        let result = self.decode_tokens(&tokens[keep..]);
        if result.is_err() {
            self.reset();
        }
        result.map(|()| keep)
    }

    /// Appends `tokens` after the cached ones; logits only for the final token.
    fn decode_tokens(&mut self, tokens: &[LlamaToken]) -> EngineResult<()> {
        let chunks = tokens.chunks(PREFILL_CHUNK);
        let last_chunk = chunks.len().saturating_sub(1);
        for (index, chunk) in chunks.enumerate() {
            let mut batch = LlamaBatch::new(chunk.len(), 1);
            let base = i32::try_from(self.cached.len()).map_err(runtime_error)?;
            for (offset, token) in chunk.iter().enumerate() {
                let position = base + i32::try_from(offset).map_err(runtime_error)?;
                let logits = index == last_chunk && offset + 1 == chunk.len();
                batch
                    .add(*token, position, &[0], logits)
                    .map_err(runtime_error)?;
            }
            self.ctx.decode(&mut batch).map_err(runtime_error)?;
            self.cached.extend_from_slice(chunk);
        }
        Ok(())
    }

    /// Forgets the cache; used when a decode failed and its state is unknown.
    fn reset(&mut self) {
        self.ctx.clear_kv_cache();
        self.cached.clear();
    }
}

impl LlamaChat {
    /// Loads a chat model, trying full GPU offload before CPU fallback.
    ///
    /// # Errors
    /// Returns [`EngineError::MissingModel`] for a missing file or a runtime error if loading fails.
    pub fn load(rt: &Runtime, path: &Path, projector: &Path) -> EngineResult<Self> {
        Self::load_with_gpu_layers(rt, path, projector, u32::MAX)
    }

    pub(crate) fn load_with_gpu_layers(
        rt: &Runtime,
        path: &Path,
        projector: &Path,
        layers: u32,
    ) -> EngineResult<Self> {
        let attempt = |gpu_layers| -> EngineResult<LlamaModel> {
            let model = load_model(rt, path, gpu_layers)?;
            let _ = context(
                &model,
                &rt.backend,
                CHAT_CONTEXT,
                false,
                LlamaPoolingType::Unspecified,
            )?;
            Ok(model)
        };
        let (model, device) = if layers == 0 {
            (attempt(0)?, "cpu")
        } else {
            match attempt(layers) {
                Ok(model) => (model, "gpu"),
                Err(error) => {
                    tracing::warn!(%error, "GPU chat model unavailable; retrying on CPU");
                    (attempt(0)?, "cpu")
                }
            }
        };
        tracing::info!(device, "loaded chat model");
        let model = Box::new(model);
        // SAFETY: the model is boxed, so its address is stable for the box's lifetime;
        // the box is never moved out of or replaced, and `LlamaChat` drops `session`
        // (the only holder of this reference) before `model`.
        let model_ref: &'static LlamaModel = unsafe { &*std::ptr::from_ref::<LlamaModel>(&model) };
        let ctx = context(
            model_ref,
            &rt.backend,
            CHAT_CONTEXT,
            false,
            LlamaPoolingType::Unspecified,
        )?;
        let mtmd = if projector.is_file() {
            let projector_path = projector.to_string_lossy();
            let params = MtmdContextParams {
                use_gpu: device == "gpu",
                n_threads: threads(),
                print_timings: false,
                ..MtmdContextParams::default()
            };
            match MtmdContext::init_from_file(&projector_path, &model, &params) {
                Ok(mtmd) => Some(Mutex::new(mtmd)),
                Err(error) => {
                    tracing::warn!(%error, "multimodal projector unavailable; audio transcription disabled");
                    None
                }
            }
        } else {
            None
        };
        Ok(Self {
            session: Mutex::new(Session {
                ctx,
                cached: Vec::new(),
            }),
            mtmd,
            model,
            backend: Arc::clone(&rt.backend),
            device,
        })
    }
    /// Reports whether the model is running with GPU or CPU placement.
    pub fn device(&self) -> &'static str {
        self.device
    }
    /// Reports whether the loaded projector supports 16 kHz audio input.
    pub fn supports_audio(&self) -> bool {
        self.mtmd.as_ref().is_some_and(|mtmd| {
            mtmd.lock().is_ok_and(|mtmd| {
                mtmd.support_audio() && mtmd.get_audio_sample_rate() == Some(16_000)
            })
        })
    }

    /// Formats the request as Gemma 4 turns and tokenizes, checking the context budget.
    fn prompt_tokens(&self, request: &ChatRequest<'_>) -> EngineResult<Vec<LlamaToken>> {
        let prompt = gemma4_prompt(Some(request.system), request.user);
        let tokens = self.model.vocab().tokenize(prompt.as_bytes(), true, true);
        let total = tokens.len().saturating_add(request.max_tokens as usize);
        if total > CHAT_CONTEXT as usize {
            return Err(EngineError::TooLong {
                tokens: total,
                limit: CHAT_CONTEXT as usize,
            });
        }
        if tokens.is_empty() {
            return Err(runtime_error("chat prompt tokenized to empty input"));
        }
        Ok(tokens)
    }

    fn sampler(&self, choices: &[String]) -> EngineResult<LlamaSampler> {
        if choices.is_empty() {
            return Ok(LlamaSampler::chain_simple([
                LlamaSampler::temp(0.2),
                LlamaSampler::dist(0),
            ]));
        }
        let grammar = LlamaSampler::grammar(&self.model, &choices_grammar(choices), "root")
            .map_err(runtime_error)?;
        Ok(LlamaSampler::chain_simple([
            grammar,
            LlamaSampler::greedy(),
        ]))
    }
}

/// Gemma 4's turn format (the GGUF's Jinja template, which llama.cpp's built-in
/// template detection does not recognise), without thinking, ending where the
/// model's reply starts. BOS is added by the tokenizer.
fn gemma4_prompt(system: Option<&str>, user: &str) -> String {
    let mut prompt = String::with_capacity(system.map_or(0, str::len) + user.len() + 64);
    if let Some(system) = system {
        prompt.push_str("<|turn>system\n");
        prompt.push_str(system);
        prompt.push_str("<turn|>\n");
    }
    prompt.push_str("<|turn>user\n");
    prompt.push_str(user);
    prompt.push_str("<turn|>\n<|turn>model\n");
    prompt
}

/// GBNF accepting exactly one of `choices`.
fn choices_grammar(choices: &[String]) -> String {
    let alternatives = choices
        .iter()
        .map(|choice| format!("\"{}\"", choice.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("root ::= {alternatives}")
}

impl ChatModel for LlamaChat {
    fn generate(
        &self,
        request: &ChatRequest<'_>,
        on_text: &mut dyn FnMut(&str) -> Flow,
    ) -> EngineResult<GenerationStats> {
        let start = Instant::now();
        let tokens = self.prompt_tokens(request)?;
        let mut sampler = self.sampler(request.choices)?;
        let mut session = self.session.lock().map_err(runtime_error)?;
        let reused = session.evaluate(&tokens)?;
        // Decoding is asynchronous on the GPU; its time shows up in `first_token_ms`.
        tracing::debug!(prompt_tokens = tokens.len(), reused, "chat prompt queued");
        let vocab = self.model.vocab();
        let mut stats = GenerationStats {
            prompt_tokens: u32::try_from(tokens.len()).unwrap_or(u32::MAX),
            ..GenerationStats::default()
        };
        let mut raw = Vec::with_capacity(8);
        let mut pending = Vec::with_capacity(4);
        for index in 0..request.max_tokens {
            // `sample` also accepts the token into the sampler (grammar state).
            let token = sampler.sample(&session.ctx, -1);
            stats.generated_tokens = index.saturating_add(1);
            if vocab.is_eog(token) {
                break;
            }
            let valid = token_text_piece(&vocab, token, &mut raw, &mut pending)?;
            if valid > 0 {
                let text = std::str::from_utf8(&pending[..valid]).map_err(runtime_error)?;
                if stats.first_token_ms == 0 {
                    stats.first_token_ms =
                        u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
                }
                let stop = on_text(text) == Flow::Stop;
                pending.drain(..valid);
                if stop {
                    break;
                }
            }
            if index + 1 < request.max_tokens {
                let decoded = session.decode_tokens(&[token]);
                if decoded.is_err() {
                    session.reset();
                }
                decoded?;
            }
        }
        if !pending.is_empty() {
            let text = String::from_utf8_lossy(&pending);
            if !text.is_empty() {
                if stats.first_token_ms == 0 {
                    stats.first_token_ms =
                        u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
                }
                let _ = on_text(&text);
            }
        }
        stats.total_ms = u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX);
        Ok(stats)
    }

    fn prefill(&self, request: &ChatRequest<'_>) -> EngineResult<()> {
        let start = Instant::now();
        let tokens = self.prompt_tokens(request)?;
        let mut session = self.session.lock().map_err(runtime_error)?;
        let reused = session.evaluate(&tokens)?;
        // Wait for the GPU so the time below is real and the work is done before the
        // question arrives.
        session.ctx.synchronize();
        tracing::debug!(
            prompt_tokens = tokens.len(),
            reused,
            prefill_ms = start.elapsed().as_millis(),
            "chat prompt prefilled"
        );
        Ok(())
    }
}

impl Transcriber for LlamaChat {
    fn transcribe(&self, pcm: &[f32], language: Language) -> EngineResult<String> {
        if pcm.len() < 4_800 {
            return Ok(String::new());
        }
        if pcm.len() > 30 * 16_000 {
            return Err(EngineError::TooLong {
                tokens: pcm.len(),
                limit: 30 * 16_000,
            });
        }
        let start = Instant::now();
        let audio_seconds = pcm.len() as f64 / 16_000.0;
        let model = &*self.model;
        let mut mtmd = self
            .mtmd
            .as_ref()
            .ok_or_else(|| runtime_error("audio projector is unavailable"))?
            .lock()
            .map_err(runtime_error)?;
        if !mtmd.support_audio() || mtmd.get_audio_sample_rate() != Some(16_000) {
            return Err(runtime_error("projector does not support 16 kHz audio"));
        }
        let bitmap = MtmdBitmap::from_audio_data(pcm).map_err(runtime_error)?;
        let instruction = match language {
            Language::English => {
                "Transcribe this audio exactly as spoken. Output only the transcript. The speaker uses English."
            }
            Language::Filipino => {
                "Transcribe this audio exactly as spoken. Output only the transcript. The speaker uses Filipino (Tagalog)."
            }
            Language::Taglish => {
                "Transcribe this audio exactly as spoken. Output only the transcript. The speaker mixes Filipino (Tagalog) and English; keep each word in the language spoken."
            }
        };
        let prompt = gemma4_prompt(None, &format!("{}{instruction}", mtmd_default_marker()));
        let chunks = mtmd
            .tokenize(
                MtmdInputText {
                    text: prompt,
                    add_special: true,
                    parse_special: true,
                },
                &[&bitmap],
            )
            .map_err(runtime_error)?;
        let mut ctx = context(
            model,
            &self.backend,
            EMBED_CONTEXT,
            false,
            LlamaPoolingType::Unspecified,
        )?;
        let n_past = chunks
            .eval_chunks(&mut mtmd, &mut ctx, 0, 0, 512, true)
            .map_err(runtime_error)?;
        let vocab = model.vocab();
        let mut sampler = LlamaSampler::greedy();
        let mut raw = Vec::with_capacity(8);
        let mut pending = Vec::with_capacity(4);
        let mut transcript = String::with_capacity(128);
        let mut batch = LlamaBatch::new(1, 1);
        for index in 0..96_i32 {
            let token = sampler.sample(&ctx, -1);
            if vocab.is_eog(token) {
                break;
            }
            let valid = token_text_piece(&vocab, token, &mut raw, &mut pending)?;
            if valid > 0 {
                let text = std::str::from_utf8(&pending[..valid]).map_err(runtime_error)?;
                transcript.push_str(text);
                pending.drain(..valid);
            }
            if index < 95 {
                batch.clear();
                batch
                    .add(token, n_past + index, &[0], true)
                    .map_err(runtime_error)?;
                ctx.decode(&mut batch).map_err(runtime_error)?;
            }
        }
        if !pending.is_empty() {
            transcript.push_str(&String::from_utf8_lossy(&pending));
        }
        tracing::debug!(
            duration_ms = u32::try_from(start.elapsed().as_millis()).unwrap_or(u32::MAX),
            audio_seconds,
            "audio transcription completed"
        );
        Ok(strip_surrounding_quotes(&transcript).to_owned())
    }
}

/// EmbeddingGemma-backed normalized vector generator.
pub struct LlamaEmbedder {
    backend: Arc<LlamaBackend>,
    model: Mutex<LlamaModel>,
    device: &'static str,
}
impl LlamaEmbedder {
    /// Loads EmbeddingGemma with mean pooling and CPU fallback.
    ///
    /// # Errors
    /// Returns [`EngineError::MissingModel`] for a missing file or a runtime error if loading fails.
    pub fn load(rt: &Runtime, path: &Path) -> EngineResult<Self> {
        Self::load_with_gpu_layers(rt, path, u32::MAX)
    }
    pub(crate) fn load_with_gpu_layers(
        rt: &Runtime,
        path: &Path,
        layers: u32,
    ) -> EngineResult<Self> {
        let attempt = |gpu_layers| -> EngineResult<LlamaModel> {
            let model = load_model(rt, path, gpu_layers)?;
            let _ = context(
                &model,
                &rt.backend,
                EMBED_CONTEXT,
                true,
                LlamaPoolingType::Mean,
            )?;
            Ok(model)
        };
        if layers == 0 {
            let model = attempt(0)?;
            tracing::info!(device = "cpu", "loaded embedding model");
            return Ok(Self {
                backend: Arc::clone(&rt.backend),
                model: Mutex::new(model),
                device: "cpu",
            });
        }
        match attempt(layers) {
            Ok(model) => {
                tracing::info!(device = "gpu", "loaded embedding model");
                Ok(Self {
                    backend: Arc::clone(&rt.backend),
                    model: Mutex::new(model),
                    device: "gpu",
                })
            }
            Err(error) => {
                tracing::warn!(%error, "GPU embedding model unavailable; retrying on CPU");
                let model = attempt(0)?;
                tracing::info!(device = "cpu", "loaded embedding model");
                Ok(Self {
                    backend: Arc::clone(&rt.backend),
                    model: Mutex::new(model),
                    device: "cpu",
                })
            }
        }
    }
    /// Reports whether the model is running with GPU or CPU placement.
    pub fn device(&self) -> &'static str {
        self.device
    }
    fn embed(&self, text: &str, prefix: &str) -> EngineResult<Vec<f32>> {
        let model = self.model.lock().map_err(runtime_error)?;
        let mut ctx = context(
            &model,
            &self.backend,
            EMBED_CONTEXT,
            true,
            LlamaPoolingType::Mean,
        )?;
        let input = format!("{prefix}{text}");
        let vocab = model.vocab();
        let tokens = vocab.tokenize(input.as_bytes(), true, true);
        if tokens.len() > EMBED_CONTEXT as usize {
            return Err(EngineError::TooLong {
                tokens: tokens.len(),
                limit: EMBED_CONTEXT as usize,
            });
        }
        if tokens.is_empty() {
            return Err(runtime_error("embedding input tokenized to empty input"));
        }
        let mut batch = LlamaBatch::new(tokens.len(), 1);
        batch
            .add_sequence(&tokens, 0, false)
            .map_err(runtime_error)?;
        ctx.decode(&mut batch).map_err(runtime_error)?;
        let vector = ctx.embeddings_seq_ith(0).map_err(runtime_error)?;
        if vector.len() < EMBEDDING_DIM {
            return Err(runtime_error(format!(
                "embedding has {} dimensions, expected at least {EMBEDDING_DIM}",
                vector.len()
            )));
        }
        let mut result = vector[..EMBEDDING_DIM].to_vec();
        let norm = result.iter().map(|value| value * value).sum::<f32>().sqrt();
        if norm.is_finite() && norm > f32::EPSILON {
            for value in &mut result {
                *value /= norm;
            }
        } else {
            return Err(runtime_error("embedding has zero or non-finite norm"));
        }
        Ok(result)
    }
}
impl Embedder for LlamaEmbedder {
    fn embed_documents(&self, texts: &[&str]) -> EngineResult<Vec<Vec<f32>>> {
        let mut result = Vec::with_capacity(texts.len());
        for text in texts {
            result.push(self.embed(text, "title: none | text: ")?);
        }
        Ok(result)
    }
    fn embed_query(&self, text: &str) -> EngineResult<Vec<f32>> {
        self.embed(text, "task: search result | query: ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    fn model_path(file: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("models")
            .join(file)
    }
    #[test]
    #[ignore = "needs model files"]
    fn chat_streams_answer_and_stats() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat model loads");
        let request = ChatRequest {
            system: "Reply with exactly the word OK",
            user: "Reply with exactly the word OK",
            max_tokens: 32,
            choices: &[],
        };
        let mut answer = String::new();
        let stats = model
            .generate(&request, &mut |piece| {
                answer.push_str(piece);
                Flow::Continue
            })
            .expect("generation succeeds");
        assert!(answer.contains("OK"));
        assert!(stats.generated_tokens > 0);
        assert!(stats.first_token_ms <= stats.total_ms);
    }
    #[test]
    #[ignore = "needs model files"]
    fn reused_prefix_picks_the_same_choice_as_a_cold_prompt() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat model loads");
        let screen = "Screen:\ne1 | button | Save\ne2 | cell | Q1, Juan Dela Cruz\ne3 | cell | Q1, Ana Santos\n\n";
        let choices = ["e1", "e2", "e3", "none"].map(String::from);
        let pick = |user: &str| {
            let mut reply = String::new();
            let request = ChatRequest {
                system: "Pick the element id where the user should act.",
                user,
                max_tokens: 8,
                choices: &choices,
            };
            model
                .generate(&request, &mut |piece| {
                    reply.push_str(piece);
                    Flow::Continue
                })
                .expect("choice generation succeeds");
            reply
        };
        let question = format!("{screen}Question: Where do I type Juan's first quarter grade?");
        model.session.lock().expect("session").reset();
        let cold = pick(&question);
        // Same prefix, different suffix, then the question again: mostly reused cache.
        let _ = pick(&format!("{screen}Question: Where is the save button?"));
        let warm = pick(&question);
        assert!(
            choices.contains(&cold),
            "reply {cold:?} is one of the choices"
        );
        assert_eq!(cold, warm);
        assert_eq!(cold, "e2");
    }
    #[test]
    #[ignore = "needs model files"]
    fn embeddings_are_normalized_and_rank_relevant_passage_higher() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaEmbedder::load(&rt, &model_path("embeddinggemma-300M-Q8_0.gguf"))
            .expect("embedding model loads");
        let docs = model
            .embed_documents(&[
                "Grading assignments requires assessing student work against a rubric.",
                "Cooking pasta requires boiling water and adding salt.",
            ])
            .expect("documents embed");
        let query = model
            .embed_query("How should I grade student assignments?")
            .expect("query embeds");
        assert_eq!(query.len(), 256);
        let norm = query.iter().map(|v| v * v).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-4);
        let cosine = |a: &[f32], b: &[f32]| a.iter().zip(b).map(|(x, y)| x * y).sum::<f32>();
        assert!(cosine(&query, &docs[0]) > cosine(&query, &docs[1]));
    }
    #[test]
    #[ignore = "needs model files"]
    fn forced_cpu_model_loads() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load_with_gpu_layers(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
            0,
        )
        .expect("CPU model loads");
        assert_eq!(model.device(), "cpu");
    }

    #[test]
    fn surrounding_quotes_are_removed() {
        assert_eq!(strip_surrounding_quotes("  \"hello\"  "), "hello");
        assert_eq!(strip_surrounding_quotes("‘hello’"), "hello");
        assert_eq!(strip_surrounding_quotes("hello"), "hello");
    }

    #[test]
    #[ignore = "needs model files"]
    fn gemma_audio_load_and_sine_transcription() {
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat and projector load");
        assert!(model.supports_audio());
        let pcm = (0..16_000)
            .map(|sample| (std::f32::consts::TAU * 440.0 * sample as f32 / 16_000.0).sin())
            .collect::<Vec<_>>();
        assert!(model.transcribe(&pcm, Language::English).is_ok());
    }

    #[test]
    #[ignore = "needs model files"]
    fn gemma_transcribes_optional_grade_fixture() {
        let wav_path = std::path::Path::new("/tmp/q_en.wav");
        if !wav_path.is_file() {
            return;
        }
        let bytes = std::fs::read(wav_path).expect("WAV fixture reads");
        assert!(bytes.len() >= 44);
        assert_eq!(&bytes[..4], b"RIFF");
        assert_eq!(&bytes[8..12], b"WAVE");
        // `say` writes extra chunks before `fmt `, so locate it instead of assuming offset 12.
        let fmt = bytes
            .windows(4)
            .position(|window| window == b"fmt ")
            .expect("WAV fmt chunk exists")
            + 8;
        let u16_at = |at: usize| u16::from_le_bytes([bytes[at], bytes[at + 1]]);
        assert_eq!(u16_at(fmt), 1, "PCM");
        assert_eq!(u16_at(fmt + 2), 1, "mono");
        assert_eq!(
            u32::from_le_bytes([
                bytes[fmt + 4],
                bytes[fmt + 5],
                bytes[fmt + 6],
                bytes[fmt + 7]
            ]),
            16_000
        );
        assert_eq!(u16_at(fmt + 14), 16, "16-bit");
        let data_offset = bytes
            .windows(4)
            .position(|window| window == b"data")
            .map(|position| position + 8)
            .expect("WAV data chunk exists");
        let pcm = bytes[data_offset..]
            .as_chunks::<2>()
            .0
            .iter()
            .map(|sample| f32::from(i16::from_le_bytes([sample[0], sample[1]])) / 32_768.0)
            .collect::<Vec<_>>();
        let rt = Runtime::init().expect("runtime initializes");
        let model = LlamaChat::load(
            &rt,
            &model_path("gemma-4-E2B-it-Q4_0.gguf"),
            &model_path("mmproj-gemma-4-E2B-it-Q8_0.gguf"),
        )
        .expect("chat and projector load");
        assert!(model.supports_audio());
        let transcript = model
            .transcribe(&pcm, Language::English)
            .expect("speech transcribes");
        assert!(transcript.to_lowercase().contains("grade"));
    }
}
