// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerLength } from "./AnswerLength";
import type { BaseRulesMode } from "./BaseRulesMode";
import type { KnowledgeBaseId } from "./KnowledgeBaseId";
import type { Language } from "./Language";

/**
 * Editable fields of an agent; the payload for create and update.
 */
export type AgentDraft = { name: string, description: string, instructions: string, baseRules: BaseRulesMode, 
/**
 * At most [`MAX_AGENT_KNOWLEDGE_BASES`].
 */
knowledgeBaseIds: Array<KnowledgeBaseId>, language: Language, answerLength: AnswerLength, 
/**
 * An id from `voice_list`; `None` uses the system default voice.
 */
voiceId: string | null, 
/**
 * 1.0 is normal speed.
 */
speechRate: number, };
