// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { Confidence } from "./Confidence";
import type { Latency } from "./Latency";
import type { PointerTarget } from "./PointerTarget";
import type { ScreenMode } from "./ScreenMode";
import type { TurnId } from "./TurnId";

export type Answer = { turnId: TurnId, question: string, text: string, citations: Array<Citation>, target: PointerTarget | null, confidence: Confidence, 
/**
 * `None` when screen help was off.
 */
screenMode: ScreenMode | null, latency: Latency, };
