// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AskInput } from "./AskInput";

export type AskRequest = { input: AskInput, 
/**
 * Read the focused app and point at an element.
 */
screenHelp: boolean, 
/**
 * Use this agent instead of the active one ("Try this agent"); nothing is saved.
 */
agentId: AgentId | null, };
