// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AskInput } from "./AskInput";
import type { TaskStep } from "./TaskStep";

export type AskRequest = { input: AskInput, 
/**
 * Read the focused app and point at an element.
 */
screenHelp: boolean, 
/**
 * Use this agent instead of the active one ("Try this agent"); nothing is saved.
 */
agentId: AgentId | null, 
/**
 * Earlier steps of a guided task, oldest first; at most MAX_TASK_STEPS - 1.
 */
task?: Array<TaskStep>, 
/**
 * "Next step" of a guided task: point at the next action of the plan made for the
 * task's first question. Any other ask starts over.
 */
nextStep?: boolean, };
