// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentId } from "./DocumentId";
import type { PassageId } from "./PassageId";

export type Citation = { 
/**
 * The `[n]` marker used in the answer text.
 */
marker: number, passageId: PassageId, documentId: DocumentId, documentName: string, 
/**
 * Page (`p. 4`) or heading path.
 */
location: string, };
