// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineComponent } from "./EngineComponent";

export type ComponentStatus = { component: EngineComponent, ready: boolean, 
/**
 * Why it is not ready (missing model file, not built on this OS, ...).
 */
detail: string | null, };
