// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentId } from "./DocumentId";
import type { DocumentKind } from "./DocumentKind";
import type { DocumentStatus } from "./DocumentStatus";
import type { KnowledgeBaseId } from "./KnowledgeBaseId";

/**
 * Emitted on [`crate::EVENT_DOCUMENT`] whenever a document changes status.
 */
export type Document = { id: DocumentId, knowledgeBaseId: KnowledgeBaseId, fileName: string, kind: DocumentKind, pageCount: number | null, passageCount: number, status: DocumentStatus, 
/**
 * Human-readable reason when `status` is `failed`.
 */
error: string | null, createdAt: number, };
