// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "notFound" | "invalid" | "duplicate" | "unavailable" | "permissionDenied" | "storage" | "engine" | "platform" | "io";
