// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeBaseId } from "./KnowledgeBaseId";
import type { KnowledgeBaseStatus } from "./KnowledgeBaseStatus";

export type KnowledgeBase = { id: KnowledgeBaseId, name: string, status: KnowledgeBaseStatus, documentCount: number, passageCount: number, 
/**
 * Unix milliseconds.
 */
createdAt: number, };
