// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measured, never estimated (BR-24). Milliseconds.
 */
export type Latency = { transcribeMs: number | null, screenMs: number | null, 
/**
 * Screenshot capture and preparation (tiers 2 and 3).
 */
captureMs: number | null, retrievalMs: number, firstTokenMs: number | null, totalMs: number, };
