// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStage } from "./DownloadStage";

export type ModelProgress = { file: string, received: number, total: number, stage: DownloadStage, error: string | null, };
