// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRole } from "./ModelRole";

export type ModelFile = { file: string, role: ModelRole, required: boolean, bytes: number, present: boolean, };
