// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A passage row; also the rowid sqlite-vector returns.
 */
export type PassageId = number;
