// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionKind } from "./PermissionKind";
import type { PermissionStatus } from "./PermissionStatus";

export type PermissionState = { kind: PermissionKind, status: PermissionStatus, };
