// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorFrame } from "./MonitorFrame";
import type { Rect } from "./Rect";

/**
 * Where the overlay should draw the gecko.
 *
 * The overlay window covers `monitor` (set it with `PhysicalPosition`/`PhysicalSize`),
 * then draws at `rect`, which is in **CSS pixels relative to that monitor's top-left**.
 */
export type PointerTarget = { 
/**
 * `None` for a tier-3 best-guess point read from a screenshot.
 */
elementId: string | null, label: string, monitor: MonitorFrame, rect: Rect, };
