// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis-aligned rectangle. The coordinate space is stated where it is used.
 */
export type Rect = { x: number, y: number, width: number, height: number, };
