// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenElement } from "./ScreenElement";

export type ScreenSnapshot = { appName: string, windowTitle: string | null, elements: Array<ScreenElement>, };
