// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the screen was given to the model for one answer (architecture: three tiers).
 */
export type ScreenMode = "elements" | "elementsWithImage" | "imageOnly";
