// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * One UI element of the focused app.
 */
export type ScreenElement = { 
/**
 * Short, snapshot-unique id the model picks by, e.g. `e12`.
 */
id: string, 
/**
 * Normalised role: `button`, `textField`, `cell`, `menuItem`, `link`, ...
 */
role: string, label: string, value: string | null, 
/**
 * **Desktop physical pixels**, origin at the primary display's top-left —
 * the same space as Tauri's `Monitor::position()` / `PhysicalPosition`.
 */
bounds: Rect, };
