// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentStatus } from "./ComponentStatus";
import type { PermissionState } from "./PermissionState";

/**
 * Everything onboarding needs to decide what to show.
 */
export type SetupStatus = { permissions: Array<PermissionState>, components: Array<ComponentStatus>, };
