// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One earlier step of a guided task, sent back by the client on "next".
 */
export type TaskStep = { question: string, answer: string, 
/**
 * Label of the element pointed at in that step, if any.
 */
targetLabel: string | null, };
