// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDraft } from "./AgentDraft";
import type { TemplateId } from "./TemplateId";

/**
 * Built-in, read-only agent blueprint (INV-8).
 */
export type Template = { id: TemplateId, draft: AgentDraft, };
