// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One question/answer turn. Monotonic per app run; never persisted.
 */
export type TurnId = number;
