// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { PointerTarget } from "./PointerTarget";
import type { TurnId } from "./TurnId";
import type { TurnPhase } from "./TurnPhase";

/**
 * Emitted on [`crate::EVENT_TURN`]. A turn ends with exactly one of
 * `finished`, `cancelled` or `failed`.
 */
export type TurnEvent = { "type": "phase", turnId: TurnId, phase: TurnPhase, } | { "type": "question", turnId: TurnId, text: string, } | { "type": "target", turnId: TurnId, target: PointerTarget | null, } | { "type": "sentence", turnId: TurnId, text: string, } | { "type": "finished", answer: Answer, } | { "type": "cancelled", turnId: TurnId, } | { "type": "failed", turnId: TurnId, message: string, };
