// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Voice = { id: string, name: string, 
/**
 * BCP-47 tag, e.g. `en-US`, `fil-PH`.
 */
language: string, };
