// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Voice = { id: string, name: string, 
/**
 * BCP-47 language tag for this voice, e.g. `en-US`.
 */
language: string, };
